# Generated by Django 3.0.3 on 2020-03-04 16:59

from django.db import migrations, models
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.SlugField(default=profiles.models.generate_id),
        ),
    ]
