# Generated by Django 3.0.4 on 2020-03-11 09:34

from django.db import migrations, models
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='slug',
            field=models.SlugField(default=profiles.models.generate_id),
        ),
    ]
