# Generated by Django 3.0.4 on 2020-03-11 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0002_registration_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='played',
            field=models.BooleanField(default=False),
        ),
    ]
