# Generated by Django 3.0.3 on 2020-03-07 10:02

from django.db import migrations, models
import django.db.models.deletion
import profiles.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0002_auto_20200304_2229'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcuthonRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.CharField(max_length=255)),
                ('team_leader', models.BooleanField(default=False)),
                ('slug', models.SlugField(default=profiles.models.generate_id, max_length=8)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event')),
            ],
        ),
    ]
