# Generated by Django 3.0.3 on 2020-03-07 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acuthon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='acuthonregister',
            name='contact',
            field=models.CharField(default=' ', max_length=10),
        ),
        migrations.AddField(
            model_name='acuthonregister',
            name='email',
            field=models.EmailField(default='acumenmember@vce.com', max_length=254),
        ),
    ]
