# Generated by Django 3.0.3 on 2020-03-08 07:58

import acuthon.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acuthon', '0003_acuthonregister_rollnumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acuthon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=acuthon.models.generate_id, max_length=100, unique=True)),
                ('slug', models.SlugField(default=acuthon.models.generate_id, max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='acuthonregister',
            name='event',
        ),
        migrations.AlterField(
            model_name='acuthonregister',
            name='slug',
            field=models.SlugField(default=acuthon.models.generate_id, max_length=8, unique=True),
        ),
    ]
