# Generated by Django 3.0.3 on 2020-03-08 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acuthon', '0004_auto_20200308_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='acuthonregister',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Acuthon', to='acuthon.Acuthon'),
        ),
    ]
