# Generated by Django 3.0.4 on 2020-03-09 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acuthon', '0005_acuthonregister_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='acuthon',
            name='college',
            field=models.CharField(default='Vasavi College of Engineering', max_length=30),
        ),
    ]
