# Generated by Django 3.0.4 on 2020-03-09 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acuthon', '0006_acuthon_college'),
    ]

    operations = [
        migrations.AddField(
            model_name='acuthonregister',
            name='college',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
